### ISSUE TITLE
Is this going to be published / what's the plan?

### ISSUE THREAD

**Issue by bgianfo** [mattco98/jakt-intellij-plugin#3]
Hello, wonderful project!

I'm just curious: 
- Do you intend to publish this, so it can be installed via the normal plugin marketplace?
- Would it make sense to contribute this to [`jakt/editors`](https://github.com/SerenityOS/jakt/tree/main/editors) with the rest of the editor plugins? Just putting the idea out there...

I'm sure someone already asked these somewhere, and I just missed it. :)

**Comment by mattco98** [comment]
> Do you intend to publish this, so it can be installed via the normal plugin marketplace?

Yeah at some point, though much like the VSCode plugin, it doesn't make much sense to do so until the language itself becomes a bit more stable. 

> Would it make sense to contribute this to [jakt/editors](https://github.com/SerenityOS/jakt/tree/main/editors) with the rest of the editor plugins? Just putting the idea out there...

Yes that is something I'd like to do, but I think I still have some work to do before that. Mostly things like documentation and a proper README, but also some design related questions like how to handle the prelude/multiple files.

**Comment by mattco98** [comment]
Well, looks like it probably won't end up being upstreamed. I guess I'll just continue to work on it here, and hopefully other people get interested on their own.

**Comment by bgianfo** [comment]
> Well, looks like it probably won't end up being upstreamed.

Why's that, did I miss something?

**Comment by mattco98** [comment]
I brought it up in discord the other day, and lack of maintenance was a concern. I'll probably bring it up again when the language gets more stable in the future.
